# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18d084e9b3c84693cb084a7b871f59532664bd2ad49cec3e704a1c59dccb052e6317f6bb5e666f5b6c6f2649765add6ceb22d69ebf252ce3a27c9903eaeb3b6f
  secret_jwt_auth: a7a74ac94c64b1cb2385439a6fb33f1fe759553d3e20906eb052d2c2f0f8bf2a97b00a87204268444042b742364f57cf1c9b11fbe75354ae042ff86a6a6a5aec
test:
  secret_key_base: c7f69e24256b47c6c3724eb4be701bcb14529138bf71403a3375f78b8a1f9155d05ce00bbdab7416d303ff7ea2e766204addc965e3393f8e99db53bf40662aa1
  secret_jwt_auth: a7a74ac94c64b1cb2385439a6fb33f1fe759553d3e20906eb052d2c2f0f8bf2a97b00a87204268444042b742364f57cf1c9b11fbe75354ae042ff86a6a6a5aec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_jwt_auth: <%= ENV["HMAC_SECRET"] %>
